services:
  db:
    container_name: inatator_db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DATABASE_URL
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  frontend:
    platform: linux/amd64
    image: umasscds/inatator_frontend:v1.1.0
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    platform: linux/amd64
    image: umasscds/inatator_backend:v1.1.0
    environment:
      - DATABASE_URL
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: 
